# Database connection strings
database:
  connection_string: "postgresql://postgres:admin@localhost/adhd_research"

# Pipeline parameters
pipeline:
  default_geo_id: "GSE85871"
  default_samples: "GSM2286316,GSM2286317,GSM2286238,GSM2286239"
  default_compound: "Gastrodin"
  default_cid: "115067"
  default_description: "Gastrodin experiment for ADHD pipeline testing"
  default_docking_center: "0, 0, 0"
  default_docking_size: "20, 20, 20"
  raw_p: 0.05
  adj_p: 0.05
  log_fc_up: 1
  log_fc_down: -1

# File paths (if needed)
paths:
  logs: "/home/scmbag/Desktop/ADHD_Compound_Pipeline/logs/"
  results: "/home/scmbag/Desktop/ADHD_Compound_Pipeline/results"
  data: "/home/scmbag/Desktop/ADHD_Compound_Pipeline/data"
  mgltools: "/home/scmbag/Desktop/ADHD_Compound_Pipeline/tools/MGLTools-1.5.7/MGLToolsPckgs/AutoDockTools/Utilities24"
