services:
  db:
    image: postgres:15
    container_name: adhd_postgres

    # Environment variables to set up the DB
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: adhd_research

    # Publish the port for db access from host or other containers
    ports:
      - "5432:5432"

    command: [ "postgres", "-c", "log_statement=all" ]

    # using named volume for persistent storage
    # mount db schema dump into the initdb directory
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./data/database_scheme/dump-adhd_research.sql:/docker-entrypoint-initdb.d/00_schema.sql
    networks:
      - adhd_network

  adhd_pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    image: adhd_pipeline:latest
    container_name: adhd_pipeline

    # block this if you don't have a gpu available
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    # Mount folder so scripts/data are accessible
    volumes:
      - ./results:/app/results_out
      #- ./scripts:/app/scripts
    working_dir: /app

    # Expose Streamlit or other ports
    ports:
      - "8501:8501"
      - "60050:60050"

    depends_on:
      - db
    # Run GUI upon startup
    command: [ "/bin/bash", "-c", "python scripts/collect_adhd_disease_genes.py && streamlit run scripts/gui_app.py --server.port=8501 --server.address=0.0.0.0" ]
    networks:
      - adhd_network

volumes:
  db_data:

networks:
  adhd_network:
    driver: bridge